version: '3.8'

services:

  backend:
    build:
      context: ./clientes
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8090:8090"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
